version: 2.1

jobs:
  build-test-python:
    parameters:
      python_version:
        description: "Python version specified as X.Y.Z"
        type: string
      python_arch:
        description: "Python arch specified as x64 or x86"
        type: string
    working_directory: /work
    docker:
      - image: dockcross/linux-<< parameters.python_arch >>
    steps:
      - checkout
      - run:
         name: download dashboard scripts
         command: |
           git clone git://github.com/python-cmake-buildsystem/python-cmake-buildsystem --branch dashboard --depth 1 scripts
      - run:
         name: build and test
         command: |
           ctest -S /work/scripts/circle_dashboard.cmake -VV
         environment:
           PY_VERSION: << parameters.python_version >>

workflows:
    build-and-test:
      jobs:
        # 3.6.7
        - build-test-python:
            name: python-3.6.7-x64
            python_version: 3.6.7
            python_arch: x64

        - build-test-python:
            name: python-3.6.7-x86
            python_version: 3.6.7
            python_arch: x86

        # 2.7.15
        - build-test-python:
            name: python-2.7.15-x64
            python_version: 2.7.15
            python_arch: x64

        - build-test-python:
            name: python-2.7.15-x86
            python_version: 2.7.15
            python_arch: x86

